# Use root/example as user/password credentials

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Alinson123
      MARIADB_DATABASE: Agiteca_db
      MARIADB_USER: Agiteca_app
      MARIADB_PASSWORD: gugu123
    ports: 
      - "3307:3306"
    volumes:
      - ./dados_mariadb:/var/lib/mysql #persistÃªncia dos dados
  adminer:
    image: adminer
    ports:
      - 8080:8080
