version: "3"
services:
  postgress_container:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"

  trino_container:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
    volumes:
      - ./catalog:/etc/trino/catalog
    depends_on:
      - postgress_container
